spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ArtTechne
    username: cos5
    password: cos1234
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  
      